package com.halove.server.service.doctor.test.model;



import java.util.Date;


public class DeviceInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.id
     *
     * @mbg.generated Tue Aug 21 12:03:17 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.MODEL
     *
     * @mbg.generated Tue Aug 21 12:03:17 CST 2018
     */
    private String model;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.SERIAL
     *
     * @mbg.generated Tue Aug 21 12:03:17 CST 2018
     */
    private String serial;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.ACTIVATED
     *
     * @mbg.generated Tue Aug 21 12:03:17 CST 2018
     */
    private Date activated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.WIFi_MAC
     *
     * @mbg.generated Tue Aug 21 12:03:17 CST 2018
     */
    private String wifiMac;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.BT_MAC
     *
     * @mbg.generated Tue Aug 21 12:03:17 CST 2018
     */
    private String btMac;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.CREATED
     *
     * @mbg.generated Tue Aug 21 12:03:17 CST 2018
     */
    private Date created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column device_info.UPDATED
     *
     * @mbg.generated Tue Aug 21 12:03:17 CST 2018
     */
    private Date updated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.id
     *
     * @return the value of device_info.id
     *
     * @mbg.generated Tue Aug 21 12:03:17 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.id
     *
     * @param id the value for device_info.id
     *
     * @mbg.generated Tue Aug 21 12:03:17 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.MODEL
     *
     * @return the value of device_info.MODEL
     *
     * @mbg.generated Tue Aug 21 12:03:17 CST 2018
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.MODEL
     *
     * @param model the value for device_info.MODEL
     *
     * @mbg.generated Tue Aug 21 12:03:17 CST 2018
     */
    public void setModel(String model) {
        this.model = model == null ? null : model.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.SERIAL
     *
     * @return the value of device_info.SERIAL
     *
     * @mbg.generated Tue Aug 21 12:03:17 CST 2018
     */
    public String getSerial() {
        return serial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.SERIAL
     *
     * @param serial the value for device_info.SERIAL
     *
     * @mbg.generated Tue Aug 21 12:03:17 CST 2018
     */
    public void setSerial(String serial) {
        this.serial = serial == null ? null : serial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.ACTIVATED
     *
     * @return the value of device_info.ACTIVATED
     *
     * @mbg.generated Tue Aug 21 12:03:17 CST 2018
     */
    public Date getActivated() {
        return activated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.ACTIVATED
     *
     * @param activated the value for device_info.ACTIVATED
     *
     * @mbg.generated Tue Aug 21 12:03:17 CST 2018
     */
    public void setActivated(Date activated) {
        this.activated = activated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.WIFi_MAC
     *
     * @return the value of device_info.WIFi_MAC
     *
     * @mbg.generated Tue Aug 21 12:03:17 CST 2018
     */
    public String getWifiMac() {
        return wifiMac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.WIFi_MAC
     *
     * @param wifiMac the value for device_info.WIFi_MAC
     *
     * @mbg.generated Tue Aug 21 12:03:17 CST 2018
     */
    public void setWifiMac(String wifiMac) {
        this.wifiMac = wifiMac == null ? null : wifiMac.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.BT_MAC
     *
     * @return the value of device_info.BT_MAC
     *
     * @mbg.generated Tue Aug 21 12:03:17 CST 2018
     */
    public String getBtMac() {
        return btMac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.BT_MAC
     *
     * @param btMac the value for device_info.BT_MAC
     *
     * @mbg.generated Tue Aug 21 12:03:17 CST 2018
     */
    public void setBtMac(String btMac) {
        this.btMac = btMac == null ? null : btMac.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.CREATED
     *
     * @return the value of device_info.CREATED
     *
     * @mbg.generated Tue Aug 21 12:03:17 CST 2018
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.CREATED
     *
     * @param created the value for device_info.CREATED
     *
     * @mbg.generated Tue Aug 21 12:03:17 CST 2018
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column device_info.UPDATED
     *
     * @return the value of device_info.UPDATED
     *
     * @mbg.generated Tue Aug 21 12:03:17 CST 2018
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column device_info.UPDATED
     *
     * @param updated the value for device_info.UPDATED
     *
     * @mbg.generated Tue Aug 21 12:03:17 CST 2018
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }
}