package com.halove.server.service.doctor.test.model;

import org.apache.ibatis.annotations.Mapper;

import java.util.Date;


public class DoctorDeviceActivation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_device_activation.ID
     *
     * @mbg.generated Fri Sep 07 09:10:34 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_device_activation.USER_ID
     *
     * @mbg.generated Fri Sep 07 09:10:34 CST 2018
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_device_activation.MODEL
     *
     * @mbg.generated Fri Sep 07 09:10:34 CST 2018
     */
    private String model;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_device_activation.IMEI
     *
     * @mbg.generated Fri Sep 07 09:10:34 CST 2018
     */
    private String imei;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_device_activation.ACTIVATED
     *
     * @mbg.generated Fri Sep 07 09:10:34 CST 2018
     */
    private Date activated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_device_activation.UUID
     *
     * @mbg.generated Fri Sep 07 09:10:34 CST 2018
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_device_activation.CREATED
     *
     * @mbg.generated Fri Sep 07 09:10:34 CST 2018
     */
    private Date created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_device_activation.UPDATED
     *
     * @mbg.generated Fri Sep 07 09:10:34 CST 2018
     */
    private Date updated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_device_activation.RESULT
     *
     * @mbg.generated Fri Sep 07 09:10:34 CST 2018
     */
    private String result;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_device_activation.ID
     *
     * @return the value of doctor_device_activation.ID
     *
     * @mbg.generated Fri Sep 07 09:10:34 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_device_activation.ID
     *
     * @param id the value for doctor_device_activation.ID
     *
     * @mbg.generated Fri Sep 07 09:10:34 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_device_activation.USER_ID
     *
     * @return the value of doctor_device_activation.USER_ID
     *
     * @mbg.generated Fri Sep 07 09:10:34 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_device_activation.USER_ID
     *
     * @param userId the value for doctor_device_activation.USER_ID
     *
     * @mbg.generated Fri Sep 07 09:10:34 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_device_activation.MODEL
     *
     * @return the value of doctor_device_activation.MODEL
     *
     * @mbg.generated Fri Sep 07 09:10:34 CST 2018
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_device_activation.MODEL
     *
     * @param model the value for doctor_device_activation.MODEL
     *
     * @mbg.generated Fri Sep 07 09:10:34 CST 2018
     */
    public void setModel(String model) {
        this.model = model == null ? null : model.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_device_activation.IMEI
     *
     * @return the value of doctor_device_activation.IMEI
     *
     * @mbg.generated Fri Sep 07 09:10:34 CST 2018
     */
    public String getImei() {
        return imei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_device_activation.IMEI
     *
     * @param imei the value for doctor_device_activation.IMEI
     *
     * @mbg.generated Fri Sep 07 09:10:34 CST 2018
     */
    public void setImei(String imei) {
        this.imei = imei == null ? null : imei.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_device_activation.ACTIVATED
     *
     * @return the value of doctor_device_activation.ACTIVATED
     *
     * @mbg.generated Fri Sep 07 09:10:34 CST 2018
     */
    public Date getActivated() {
        return activated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_device_activation.ACTIVATED
     *
     * @param activated the value for doctor_device_activation.ACTIVATED
     *
     * @mbg.generated Fri Sep 07 09:10:34 CST 2018
     */
    public void setActivated(Date activated) {
        this.activated = activated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_device_activation.UUID
     *
     * @return the value of doctor_device_activation.UUID
     *
     * @mbg.generated Fri Sep 07 09:10:34 CST 2018
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_device_activation.UUID
     *
     * @param uuid the value for doctor_device_activation.UUID
     *
     * @mbg.generated Fri Sep 07 09:10:34 CST 2018
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_device_activation.CREATED
     *
     * @return the value of doctor_device_activation.CREATED
     *
     * @mbg.generated Fri Sep 07 09:10:34 CST 2018
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_device_activation.CREATED
     *
     * @param created the value for doctor_device_activation.CREATED
     *
     * @mbg.generated Fri Sep 07 09:10:34 CST 2018
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_device_activation.UPDATED
     *
     * @return the value of doctor_device_activation.UPDATED
     *
     * @mbg.generated Fri Sep 07 09:10:34 CST 2018
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_device_activation.UPDATED
     *
     * @param updated the value for doctor_device_activation.UPDATED
     *
     * @mbg.generated Fri Sep 07 09:10:34 CST 2018
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_device_activation.RESULT
     *
     * @return the value of doctor_device_activation.RESULT
     *
     * @mbg.generated Fri Sep 07 09:10:34 CST 2018
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_device_activation.RESULT
     *
     * @param result the value for doctor_device_activation.RESULT
     *
     * @mbg.generated Fri Sep 07 09:10:34 CST 2018
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }
}