package com.halove.server.service.doctor.test.model;

import org.apache.ibatis.annotations.Mapper;

import java.util.Date;


public class UserIdcard {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_idcard.ID_USER
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    private Long idUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_idcard.NAME
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_idcard.NUMBER
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    private String number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_idcard.EXPIRE_DATE
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    private Date expireDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_idcard.ADDRESS
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_idcard.ID_USER
     *
     * @return the value of user_idcard.ID_USER
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    public Long getIdUser() {
        return idUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_idcard.ID_USER
     *
     * @param idUser the value for user_idcard.ID_USER
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    public void setIdUser(Long idUser) {
        this.idUser = idUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_idcard.NAME
     *
     * @return the value of user_idcard.NAME
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_idcard.NAME
     *
     * @param name the value for user_idcard.NAME
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_idcard.NUMBER
     *
     * @return the value of user_idcard.NUMBER
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_idcard.NUMBER
     *
     * @param number the value for user_idcard.NUMBER
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_idcard.EXPIRE_DATE
     *
     * @return the value of user_idcard.EXPIRE_DATE
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    public Date getExpireDate() {
        return expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_idcard.EXPIRE_DATE
     *
     * @param expireDate the value for user_idcard.EXPIRE_DATE
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    public void setExpireDate(Date expireDate) {
        this.expireDate = expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_idcard.ADDRESS
     *
     * @return the value of user_idcard.ADDRESS
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_idcard.ADDRESS
     *
     * @param address the value for user_idcard.ADDRESS
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }
}