package com.halove.server.service.doctor.test.model;



import java.util.Date;


public class UserMember {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_member.ID
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_member.IM_USER_NAME
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    private String imUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_member.MOBILE
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_member.PASSWORD
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_member.ONLINE_STATUS
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    private Short onlineStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_member.REALNAME
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    private String realname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_member.NICKNAME
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_member.HEAD_PIC
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    private Long headPic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_member.EMAIL
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_member.QQ
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    private String qq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_member.WE_CHAT
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    private String weChat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_member.CREATE_TIME
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_member.update_time
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_member.TYPE
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    private Short type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_member.CREATE_STATUS
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    private Short createStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_member.GENDER
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    private Short gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_member.HEIGHT
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    private Short height;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_member.WEIGHT
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    private Short weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_member.BIRTH
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    private Date birth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_member.CITY
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_member.IS_DEVELOPER
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    private Integer isDeveloper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_member.long_habitat
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    private String longHabitat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_member.HAS_WRISTBAND
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    private Short hasWristband;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_member.USE_9I_PHONE
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    private Short use9iPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_member.IS_EXPERIENCE
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    private Short isExperience;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_member.src
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    private String src;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_member.ID
     *
     * @return the value of user_member.ID
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_member.ID
     *
     * @param id the value for user_member.ID
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_member.IM_USER_NAME
     *
     * @return the value of user_member.IM_USER_NAME
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    public String getImUserName() {
        return imUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_member.IM_USER_NAME
     *
     * @param imUserName the value for user_member.IM_USER_NAME
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    public void setImUserName(String imUserName) {
        this.imUserName = imUserName == null ? null : imUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_member.MOBILE
     *
     * @return the value of user_member.MOBILE
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_member.MOBILE
     *
     * @param mobile the value for user_member.MOBILE
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_member.PASSWORD
     *
     * @return the value of user_member.PASSWORD
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_member.PASSWORD
     *
     * @param password the value for user_member.PASSWORD
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_member.ONLINE_STATUS
     *
     * @return the value of user_member.ONLINE_STATUS
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    public Short getOnlineStatus() {
        return onlineStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_member.ONLINE_STATUS
     *
     * @param onlineStatus the value for user_member.ONLINE_STATUS
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    public void setOnlineStatus(Short onlineStatus) {
        this.onlineStatus = onlineStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_member.REALNAME
     *
     * @return the value of user_member.REALNAME
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_member.REALNAME
     *
     * @param realname the value for user_member.REALNAME
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_member.NICKNAME
     *
     * @return the value of user_member.NICKNAME
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_member.NICKNAME
     *
     * @param nickname the value for user_member.NICKNAME
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_member.HEAD_PIC
     *
     * @return the value of user_member.HEAD_PIC
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    public Long getHeadPic() {
        return headPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_member.HEAD_PIC
     *
     * @param headPic the value for user_member.HEAD_PIC
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    public void setHeadPic(Long headPic) {
        this.headPic = headPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_member.EMAIL
     *
     * @return the value of user_member.EMAIL
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_member.EMAIL
     *
     * @param email the value for user_member.EMAIL
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_member.QQ
     *
     * @return the value of user_member.QQ
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_member.QQ
     *
     * @param qq the value for user_member.QQ
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_member.WE_CHAT
     *
     * @return the value of user_member.WE_CHAT
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    public String getWeChat() {
        return weChat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_member.WE_CHAT
     *
     * @param weChat the value for user_member.WE_CHAT
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    public void setWeChat(String weChat) {
        this.weChat = weChat == null ? null : weChat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_member.CREATE_TIME
     *
     * @return the value of user_member.CREATE_TIME
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_member.CREATE_TIME
     *
     * @param createTime the value for user_member.CREATE_TIME
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_member.update_time
     *
     * @return the value of user_member.update_time
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_member.update_time
     *
     * @param updateTime the value for user_member.update_time
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_member.TYPE
     *
     * @return the value of user_member.TYPE
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    public Short getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_member.TYPE
     *
     * @param type the value for user_member.TYPE
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    public void setType(Short type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_member.CREATE_STATUS
     *
     * @return the value of user_member.CREATE_STATUS
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    public Short getCreateStatus() {
        return createStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_member.CREATE_STATUS
     *
     * @param createStatus the value for user_member.CREATE_STATUS
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    public void setCreateStatus(Short createStatus) {
        this.createStatus = createStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_member.GENDER
     *
     * @return the value of user_member.GENDER
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    public Short getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_member.GENDER
     *
     * @param gender the value for user_member.GENDER
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    public void setGender(Short gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_member.HEIGHT
     *
     * @return the value of user_member.HEIGHT
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    public Short getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_member.HEIGHT
     *
     * @param height the value for user_member.HEIGHT
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    public void setHeight(Short height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_member.WEIGHT
     *
     * @return the value of user_member.WEIGHT
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    public Short getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_member.WEIGHT
     *
     * @param weight the value for user_member.WEIGHT
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    public void setWeight(Short weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_member.BIRTH
     *
     * @return the value of user_member.BIRTH
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    public Date getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_member.BIRTH
     *
     * @param birth the value for user_member.BIRTH
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    public void setBirth(Date birth) {
        this.birth = birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_member.CITY
     *
     * @return the value of user_member.CITY
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_member.CITY
     *
     * @param city the value for user_member.CITY
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_member.IS_DEVELOPER
     *
     * @return the value of user_member.IS_DEVELOPER
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    public Integer getIsDeveloper() {
        return isDeveloper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_member.IS_DEVELOPER
     *
     * @param isDeveloper the value for user_member.IS_DEVELOPER
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    public void setIsDeveloper(Integer isDeveloper) {
        this.isDeveloper = isDeveloper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_member.long_habitat
     *
     * @return the value of user_member.long_habitat
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    public String getLongHabitat() {
        return longHabitat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_member.long_habitat
     *
     * @param longHabitat the value for user_member.long_habitat
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    public void setLongHabitat(String longHabitat) {
        this.longHabitat = longHabitat == null ? null : longHabitat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_member.HAS_WRISTBAND
     *
     * @return the value of user_member.HAS_WRISTBAND
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    public Short getHasWristband() {
        return hasWristband;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_member.HAS_WRISTBAND
     *
     * @param hasWristband the value for user_member.HAS_WRISTBAND
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    public void setHasWristband(Short hasWristband) {
        this.hasWristband = hasWristband;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_member.USE_9I_PHONE
     *
     * @return the value of user_member.USE_9I_PHONE
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    public Short getUse9iPhone() {
        return use9iPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_member.USE_9I_PHONE
     *
     * @param use9iPhone the value for user_member.USE_9I_PHONE
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    public void setUse9iPhone(Short use9iPhone) {
        this.use9iPhone = use9iPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_member.IS_EXPERIENCE
     *
     * @return the value of user_member.IS_EXPERIENCE
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    public Short getIsExperience() {
        return isExperience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_member.IS_EXPERIENCE
     *
     * @param isExperience the value for user_member.IS_EXPERIENCE
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    public void setIsExperience(Short isExperience) {
        this.isExperience = isExperience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_member.src
     *
     * @return the value of user_member.src
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    public String getSrc() {
        return src;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_member.src
     *
     * @param src the value for user_member.src
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    public void setSrc(String src) {
        this.src = src == null ? null : src.trim();
    }
}