package com.halove.server.service.doctor.test.mappers;

import com.halove.server.service.doctor.test.model.DeviceInfo;

public interface IDeviceInfo {

    int insertSelective(DeviceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_info
     *
     * @mbg.generated Tue Aug 21 12:03:17 CST 2018
     */
    DeviceInfo selectByPrimaryKey(Long id);
}