package com.halove.server.service.doctor.test.mappers;


import com.halove.server.service.doctor.test.model.DoctorDeviceInfo;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface IDoctorDeviceInfo {


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_device_info
     *
     * @mbg.generated Wed Aug 22 15:19:49 CST 2018
     */
    int insertSelective(DoctorDeviceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_device_info
     *
     * @mbg.generated Wed Aug 22 15:19:49 CST 2018
     */
    DoctorDeviceInfo selectByPrimaryKey(Long id);
}