package com.halove.server.service.doctor.test.mappers;


import com.halove.server.service.doctor.test.model.DoctorDeviceActivation;

public interface IDoctorDeviceActivation {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_device_activation
     *
     * @mbg.generated Fri Sep 07 09:10:34 CST 2018
     */
    int insert(DoctorDeviceActivation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_device_activation
     *
     * @mbg.generated Fri Sep 07 09:10:34 CST 2018
     */
    int insertSelective(DoctorDeviceActivation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doctor_device_activation
     *
     * @mbg.generated Fri Sep 07 09:10:34 CST 2018
     */
    DoctorDeviceActivation selectByPrimaryKey(Long id);
}