package com.halove.server.service.doctor.test.mappers;



import com.halove.server.service.doctor.test.model.UserMember;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface IUserMember {


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_member
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    int insertSelective(UserMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_member
     *
     * @mbg.generated Wed Aug 15 09:58:35 CST 2018
     */
    UserMember selectByPrimaryKey(Long id);
}